spring:
  application:
    name: appointment-service
  datasource:
    url: jdbc:postgresql://localhost:5432/appointment_db
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8083

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/


resilience4j:
  circuitbreaker:
    instances:
      doctorServiceCB:
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3

logging:
  level:
    io.github.resilience4j: INFO